config/routes.rb
Rails.application.routes.draw do


  root 'welcome#home'
  
  get 'auth/:provider/callback',  to: 'sessions#create_from_omniauth'
  resources :animals do
    resources :reports
  end

  resources :users do
    resources :reports
  end
  resources :users
  resources :reports
  resources :sections, only: [:index] do
    resources :users, only: [:new, :show]
  end

  get 'animalhr', to: 'animals#animalhr'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout'  => 'sessions#destroy'

  resources :animals
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
    belongs_to :section
    has_many :reports
    has_many :users, through: :reports
    validates :name, presence: true
    scope :search, -> (query) {where("name LIKE ?",  "%#{query}%")}
    accepts_nested_attributes_for :reports
    
    # def self.search(query)
    #     where("name like ?", "%#{query}%")
    #   end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord
    belongs_to :user
    belongs_to :animal
    validates :topic, presence: true
    validates :observations, presence: true

end

app/models/section.rb
class Section < ApplicationRecord
    has_many :users
    has_many :animals

end

#Create a section on user sign up page, or choose preseeded data on a drop down menu in a form_with with fields_for 
#for creating a new user.
#If you are signing in through omniauth you will be redirected to a form with prefilled username.
#Section has_many users, assign the section_id to users.

app/models/user.rb
class User < ApplicationRecord
    belongs_to :section
    has_many :reports
    has_many :animals, through: :reports
    validates :username, presence: true
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
    validate :password_requirements_are_met
    

    accepts_nested_attributes_for :reports
    has_secure_password



    def self.from_omniauth(auth)
        #byebug
        find_or_create_by(username: auth[:info][:name]) do |user|
            user.password = SecureRandom.hex(15)
        end
        # create! do |user|
        #   user.provider = auth["provider"]
        #   user.uid = auth["uid"]
        #   user.name = auth["info"]["name"]
        # end
      end

      def password_requirements_are_met
        rules = {
          " must contain at least one lowercase letter"  => /[a-z]+/,
          " must contain at least one uppercase letter"  => /[A-Z]+/,
          " must contain at least one digit"             => /\d+/,
          " must contain at least one special character" => /[^A-Za-z0-9]+/
        }
      
        rules.each do |message, regex|
          errors.add( :password, message ) unless password.match( regex )
        end
      end
    
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
    before_action :require_login
    
    def index
        
        if params[:query]
            @animals = Animal.search(params[:query])
          else
            @animals = Animal.all
          end
    
    end
    
    def new
        @animal = Animal.new
    end

    def create
        @animal = Animal.new(animal_params)
        if @animal.save
            redirect_to new_report_path
        else
            render :new
        end
    end
    

    def show
        @animal = Animal.find_by(:id => params[:id])
    end

    def animalhr
        @animals = Animal.all
    end

    
    private

    def animal_params
        params.require(:animal).permit(:name, :health_rating, :section_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :require_login

    private
  def current_user
    # The session[:user_id] has been set
    if session[:user_id].present?
      @user = User.find_by(:id => session[:user_id])
    end
  end

  def require_login
    unless current_user
      redirect_to root_url
    end
  end


end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
    before_action :current_user
    before_action :set_report, only: [:show, :edit, :update, :destroy]
    before_action :require_login
    
    def index
        if get_animal
            @reports = get_animal.reports
        
        end
             
           
    end
    
    def new
        
        @report = @user.reports.build
    end

    def create
       
            @report = @user.reports.build(report_params)
                if @report.save 
                    redirect_to user_path(@user)
                else
                    render :new
                end
       
    end

    def edit

    end

    def update

       if @report.update(report_params)
           redirect_to user_path(@user)
        
       else
           render :edit
          
       end
    end

    def destroy
       @report.destroy
       redirect_to user_path(@user)
    end

    def show
        @animal = get_animal
    end

    private

    def get_animal
        @animal = Animal.find_by(id: params[:animal_id])
    end
    
    def report_params
        params.require(:report).permit(:topic, :observations, :user_id, :animal_id, :query)
    end

    def set_report
        @report = @user.reports.find(params[:id])
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

    def index
        @sections = Section.all
    end
    
    def new
        @section = Section.new
    end

    def create
        @section = Section.new(section_params)
        @section.user_id = current_user.id
        if @section.save
            redirect_to section_path(@section)
        else
            render :new
        end
    end

    def show 
        @section =  Section.find_by(:id => params[:id])
    end

    private

    def section_params
        params.require(:section).permit(:name, :environment)
    end
    
    #create all the actions so I can navigate through the views 
    #this includes creating links between views
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :create

  def new
  end
  
  def create_from_omniauth
    @user = User.from_omniauth(auth)
    #byebug
    if @user
      session[:user_id] = @user.id
      render '/users/edit'
    else
      flash[:notice] = 'Google Login Failed'
      redirect_to '/users/new'

    end
    
  end

  def create
    
    @user = User.find_by(:username => params[:username])
    
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
          flash[:notice] = "Login Failed"
          redirect_to '/login'
      end
  end

        def destroy
          if current_user
            session.delete :user_id
            redirect_to root_url
          end
        end
       
        private
       
        def auth
          request.env['omniauth.auth']
        end
      
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, except: [:new, :create]


    

    def new

      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      # params.delete(:section_id)
      # byebug
      if @user.save
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        #byebug
        render :new
      end
    end
  
    def show
      @user = User.find_by(:id => params[:id])
    end

    def edit
      @user = User.find_by(name: username)
    
    end

    def update

      if @user.update(user_params)
          redirect_to user_path(@user)
       
      else
          render :edit
         
      end
   end

  
  private
  def user_params
    params.require(:user).permit(:username, :role, :email, :password, :password_confirmation, :experience_lvl, :section_id)
  end
 


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/animalhr.html.erb
<h1>List of all animals and their helth ratings </h1>

<ul>
<% @animals.each do |animal| %>
   <li> <%= animal.name %></li> 
   <li> <%= animal.health_rating %></li> 
   <% end %>
   </ul>

app/views/animals/index.html.erb
<h1> Search Reports by Animal </h1>


<%= form_tag(animals_path, method: "get") do %>
    <%= label_tag(:query, "Search by name of animal:") %>
    <%= text_field_tag(:query) %>
    <%= submit_tag("Search") %>
  <% end %>


<h1>Search Results:</h1>
<h3><% @animals.order(:name).each do |animal| %>
  <p><%=link_to animal.name, animal_reports_path(animal)%></p>
<% end %></h3>
<%= link_to "Add a new animal for observation", new_animal_path %>

app/views/animals/new.html.erb
<%= form_with model: @animal do |animal_form| %>
    Name: <%= animal_form.text_field :name %>
    Health rating: <%= animal_form.number_field :health_rating, min: 1, max: 100 %>
  
    Section:  <%= animal_form.collection_select(:section_id, Section.all, :id, :name) %>

      <%= animal_form.submit %>
      <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZooApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
        <a class="navbar-brand" href="<%= new_user_path %>"/>Sign Up</a>
        <% if current_user %>
        <a class="navbar-brand" href="<%= logout_path %>"/>Log Out</a>
        <% else %>
        <a class="navbar-brand" href="<%= login_path %>"/>Log In</a>
        <% end %>
        
       
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- content -->
    <div class="container"  role="main">
    <br>
<br>
<br>
<br>
      <%= yield %>
    </div>
  </body>
</html>

app/views/reports/_form.html.erb
<%= form_with(model: [@animal, report], local: true) do |report_form| %>

  <% if @report.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@report.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>
 
    <ul>
    <% @report.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

    Topic: <%= report_form.text_field :topic %>
    Observations: <%= report_form.text_area :observations %>
    
    <% if !@animal %>
    Animal Name: <%= report_form.collection_select(:animal_id, Animal.all, :id, :name) %>
    <% end %>
      <%= report_form.submit %>
      <% end %>

app/views/reports/_report.html.erb
<%= form_with(model: [@animal, report], local: true) do |report_form| %>
    Topic: <%= report_form.text_field :topic %>
    Observations: <%= report_form.text_area :observations %>
    <% if !@animal %>
    Animal Name: <%= report_form.collection_select(:animal_id, Animal.all, :id, :name) %>
    <% end %>
      <%= report_form.submit %>
      <% end %>

app/views/reports/_reports.html.erb
    <br>
        <br>
        Report submitted by:
        <%= report.user.username %>
        <br>
        Report submitted on: 
        <%= report.animal.name %>
        <br>
        Topic: 
        <%= report.topic %>
        <br>
        Observations: 
        <%= report.observations %>
        <br>
        <br>
        
      
   

app/views/reports/edit.html.erb
<h1>Edit a report on the animals you work with.</h1>

<%= render partial: "form", locals: {report: @report} %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports on <%= @animal.name %></h1>
<br>

<br>
<table>
  <thead>
    <tr>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>

<%= render partial: 'reports', locals: {report: report} %>
 <% end %>
  </tbody>
</table>



  <%= link_to 'Back to User Account', [@user] %>
  <br>
 
       
  </tr>
</table>

<br>

<%= link_to 'New Report', new_animal_report_path(@user) %>

app/views/reports/new.html.erb
<h1>Create a new report on the animals you work with.</h1>

<%= render partial: "form", locals: {animal: @animal, report: @report} %>

<%= link_to "Click here if you are working with animals not listed.", new_animal_path %>

app/views/reports/show.html.erb
<h1> Reports already submitted on <%= @animal.name %> </h1>


 Health Rating: <%= @animal.health_rating %><br>
 <% @animal.reports.each do |report| %>

    <%= render partial: 'reports', locals: {report: report} %>
     <% end %>
<br>
 <%= link_to "Back to species index",  animals_path %>
 <br> 

app/views/sections/_section.html.erb
<% if @section.user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@section.user.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>
 
    <ul>
    <% @section.user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: section do |section_form| %>
    Name: <%= section_form.collection_select(:user_id, Section.all, :id, :name) %>
    Environment: <%= section_form.collection_select(:user_id, Section.all, :id, :environment) %>
    <% fields_for :user, section.user do |user_form| %>
      Username: <%= user_form.text_field :username %>
      Email: <%= user_form.email_field :email %>
      Password: <%= user_form.password_field :password %>
      Password Confirmation: <%= user_form.password_field :password_confirmation %>
      Role: <%= user_form.text_field :role %>
      Experience Level(number of years): <%= user_form.number_field :experience_lvl %>
      <% end %>

      <%= section_form.submit %>
      <% end %>

app/views/users/_user.html.erb
  

   <%= form_with model: user, local: true do |user_form| %>
    
    <% if @user.errors.any? %>
   <div id="error_explanation">
     <h2>
       <%= pluralize(@user.errors.count, "error") %>
       prohibited this user from being saved:
     </h2>
  
     <ul>
     <% @user.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

    Username: <%= user_form.text_field :username %>
    Email: <%= user_form.email_field :email %>

    <div class="field<%= ' field_with_errors' if @user.errors[:password].any? %>">
    Password: <%= user_form.password_field :password %>
    </div>
    
    Password Confirmation: <%= user_form.password_field :password_confirmation %>
    Role: <%= user_form.text_field :role %>
    Section Name: <%= user_form.collection_select(:section_id, Section.all, :id, :name) %>
    Experience Level(number of years): <%= user_form.number_field :experience_lvl %>
      <%= user_form.submit %>
      <% end %>

    
 

app/views/users/edit.html.erb
<h1>Add Zookeeper/User Info</h1>

<%= @user.username %>

<%= render partial: "users/user", locals: {user: @user} %>

app/views/users/index.html.erb
<h1>'Welcome to the Natural Environment for Animals in Zoos WorkStudy.'</h1>






<h2> 'If you are a current zoo caregiver, please login.' </h2>

<% if session[:user_id] %>
  <h1><%= @user.name %></h1>
  <h2>Email: <%= @user.email %></h2>
  <h2>Facebook UID: <%= @user.uid %></h2>
  <img src="<%= @user.image %>">
<% else %>
     <%= link_to('Sign up on our website.', user_new_path) %>
  <%= link_to('Log in with Facebook.', '/auth/facebook') %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render partial: "user", locals: {user: @user} %>
<br>
Password:
 - must contain at least one lowercase letter 
 - must contain at least one uppercase letter 
 - must contain at least one digit  
 - must contain at least one special character




   
 

app/views/users/show.html.erb
<h1> Welcome to your Zookeeper Account, <%= @user.username %><br></h1> 





<%= @user.username %><br>
 Role: <%= @user.role %><br>
 Experience in years: <%= @user.experience_lvl %><br>
 Email: <%= @user.email %><br>
 Section name: <%= @user.section.name %><br>
 Section environment: <%= @user.section.environment %><br>
 <br>
<br>
 <%= link_to "Create a report for the animals you work with",  new_user_report_path(@user) %>
 <br> 
 <br>

 <br>
 <%= link_to "Search reports by name of species", animals_path %>
<br>


 <h2>All my reports </h2>

 <table>
  <thead>
    <tr>
      
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
<% @user.reports.each do |report| %>

<%= render partial: 'reports/reports', locals: {user: @user, report: report} %>
 
<%= link_to 'Edit Post', edit_user_report_path(@user, report) %>
<br>
<%= link_to 'Destroy Post', [@user, report], method: :delete, data: { confirm: 'Are you sure?' } %>

<% end %>
</tbody>
</table>

app/views/welcome/home.html.erb
<h1>'Welcome to the Natural Environment for Animals in Zoos WorkStudy.'</h1>



<% if current_user %>
    <h1>You are Logged In: </h1>
    <%= link_to current_user.username, user_path(current_user) %>
<%end%>


<h2> 'If you are a current zoo caregiver, please login.' </h2>
<%= link_to "Login", '/login' %> 


<%= button_to "Sign in with Google", "/auth/google_oauth2" %>
<%= link_to "Create an Account", new_user_path %>
  